apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    clusterName: sportify
    environmentGitOwner: 4-cube
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: eks
    region: eu-west-1
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: secretsManager
  vault:
    aws:
      autoCreate: true
      iamUserName: marko

    disableURLDiscovery: true
  webhook: lighthouse
